### ISSUE TITLE
function pg_get_table_distributedby() behavior

### ISSUE THREAD

**Issue by charliettxx** [QingMa-gp/fix_distribution_policy#3]
I saw we used pg_get_table_distributedby() in our script, there is a strange behavior about this function as we turn off/on guc
gp_use_legacy_hashops, I'm not sure whether it will affect our script result or not, I tend to No.

### Repro
version 6X_STABLE
```
-- make sure we use legacy hash opclass
postgres=# set gp_use_legacy_hashops = on;
SET
postgres=# create table t1(a int, b int, c int);

-- then we set gp_use_legacy_hashops off/on, it shows different result
postgres=# set gp_use_legacy_hashops = on;
SET
postgres=# select pg_get_table_distributedby(oid) from pg_class where relname = 't1';
 pg_get_table_distributedby 
----------------------------
 DISTRIBUTED BY (a)
(1 row)

postgres=# set gp_use_legacy_hashops = off;
SET
postgres=# select pg_get_table_distributedby(oid) from pg_class where relname = 't1';
     pg_get_table_distributedby      
-------------------------------------
 DISTRIBUTED BY (a cdbhash_int4_ops)
(1 row)
```
Does it matter for our script?

**Comment by kainwen** [comment]
The python script will remove ops when generating SQLs, see https://github.com/QingMa-gp/fix_distribution_policy/blob/main/fix_distribution_policy.py#L88

Function `def remove_ops_ifany(self, distby):`
